apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match <plural>.<group>
  name: foos.fearofoblivion.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: fearofoblivion.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "A foo object"
          properties:
            data:
              type: object
              properties:
                value1:
                  type: string
                value2:
                  type: string
                  pattern: "^[a-zA-Z0-9]+"
                value3:
                  type: integer
                value4:
                  type: integer
                  minimum: 1
                  maximum: 10
                  default: 1
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
    ## shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    # - ct